services:
  caddy:
    container_name: caddy
    build: ./
    env_file:
      - .env
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  ui:
    container_name: ui
    build: ./ui
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  caddy_data:
  caddy_config:
networks:
  default:
    name: local